{
 "title": "Stock portfolio",
 "description": "Stock portfolio  Overview",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-2m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(stock_price, stock_symbol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All stock values",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "stock_price{stock_symbol=~\"$target\"}",
     "legendFormat": "{{ stock_symbol }}"
    }
   ]
  },
  { "title": "$target ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "target" },
  {
   "title": "EPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stock_eps{stock_symbol=\"$target\"}"
    }
   ]
  },
  {
   "title": "Stock Price",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 9 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "stock_price{stock_symbol=\"$target\"}",
     "legendFormat": "{{ stock_symbol }}"
    }
   ]
  },
  {
   "title": "DIVIDEND",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stock_dividend{stock_symbol=\"$target\"}"
    }
   ]
  },
  {
   "title": "Market Cap(Bil)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 10, "x": 3, "y": 15 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "stock_market_cap{stock_symbol=\"$target\"}"
    }
   ]
  },
  {
   "title": "Stock Volume",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "stock_volume{stock_symbol=\"$target\"}"
    }
   ]
  }
 ]
}